# Generated by Django 5.2.8 on 2025-12-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='cerated_at',
            new_name='created_at',
        ),
    ]
